### ISSUE TITLE
Fix noVNC dependency

### ISSUE THREAD

**Issue by niqdev** [edgelevel/alpine-xfce-vnc#1]
noVNC is failing to start
```
supervisorctl status
novnc                            FATAL     Exited too quickly (process log may have details)
x11vnc                           RUNNING   pid 58, uptime 0:04:24
xfce4                            RUNNING   pid 9, uptime 0:04:25
xvfb                             RUNNING   pid 11, uptime 0:04:25
```

due to the following dependency
```
Traceback (most recent call last):
  File "/usr/bin/websockify", line 33, in <module>
    sys.exit(load_entry_point('websockify==0.9.0', 'console_scripts', 'websockify')())
  File "/usr/bin/websockify", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: websockify
Failed to start WebSockets proxy
```

To manually solve the issue, install `pip` and upgrade `pip3 install websockify` to version `0.10.0`

See
* https://git.alpinelinux.org/aports/tree/testing/novnc/APKBUILD
* https://git.alpinelinux.org/aports/tree/testing/websockify/APKBUILD

**Comment by niqdev** [comment]
Current status: contacted the maintainer of the websockify package to upgrade it
